# Localized messages for the inforapp widget plugin. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.


###########################################################
# Choice types

	
Choices.acButtonState.disabled=Desactivado
Choices.acButtonState.normal=Normal

Choices.acIconPosition.left=Izquierda
Choices.acIconPosition.right=Derecha
Choices.acIconPosition.top=Superior
Choices.acIconPosition.bottom=Inferior

Choices.acIconSize.small=Pequeña
Choices.acIconSize.medium=Media
Choices.acIconSize.large=Grande


###########################################################
# Widget elements

AcIconElement=Icono
AcLabelWidget=Etiqueta
AcButtonWidget=Botón
AcNavBarWidget=TabBar
AcListWidget=Lista
AcChartWidget=Diagrama
AcCustomWidget=Personalizar
