# Localized messages for the inforapp widget plugin. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.


###########################################################
# Choice types

	
Choices.acButtonState.disabled=사용 안 함
Choices.acButtonState.normal=기본

Choices.acIconPosition.left=왼쪽
Choices.acIconPosition.right=오른쪽
Choices.acIconPosition.top=위쪽
Choices.acIconPosition.bottom=아래쪽

Choices.acIconSize.small=작게
Choices.acIconSize.medium=보통
Choices.acIconSize.large=크게


###########################################################
# Widget elements

AcIconElement=아이콘
AcLabelWidget=레이블
AcButtonWidget=단추
AcNavBarWidget=TabBar
AcListWidget=목록
AcChartWidget=차트
AcCustomWidget=사용자 지정
