# Localized messages for the inforapp widget plugin. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.


###########################################################
# Choice types

	
Choices.acButtonState.disabled=Désactivé
Choices.acButtonState.normal=Normal

Choices.acIconPosition.left=Gauche
Choices.acIconPosition.right=Droite
Choices.acIconPosition.top=Haut
Choices.acIconPosition.bottom=Bas

Choices.acIconSize.small=Petite
Choices.acIconSize.medium=Moyenne
Choices.acIconSize.large=Large


###########################################################
# Widget elements

AcIconElement=Icône
AcLabelWidget=Etiquette
AcButtonWidget=Bouton
AcNavBarWidget=Barre d'onglets
AcListWidget=Liste
AcChartWidget=Graphique
AcCustomWidget=Personnalisé
