# Localized messages for the inforapp widget plugin. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.


###########################################################
# Choice types

	
Choices.acButtonState.disabled=Deaktiviert
Choices.acButtonState.normal=Normal

Choices.acIconPosition.left=Links
Choices.acIconPosition.right=Rechts
Choices.acIconPosition.top=Oben
Choices.acIconPosition.bottom=Unten

Choices.acIconSize.small=Klein
Choices.acIconSize.medium=Mittel
Choices.acIconSize.large=Groﬂ


###########################################################
# Widget elements

AcIconElement=Symbol
AcLabelWidget=Beschriftung
AcButtonWidget=Schaltfl‰che
AcNavBarWidget=TabBar
AcListWidget=Liste
AcChartWidget=Diagramm
AcCustomWidget=Benutzerdefiniert
