# Localized messages for the inforapp widget plugin. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.


###########################################################
# Choice types

	
Choices.acButtonState.disabled=已禁用
Choices.acButtonState.normal=正常

Choices.acIconPosition.left=靠左
Choices.acIconPosition.right=靠右
Choices.acIconPosition.top=顶部
Choices.acIconPosition.bottom=底部

Choices.acIconSize.small=小
Choices.acIconSize.medium=中等
Choices.acIconSize.large=大


###########################################################
# Widget elements

AcIconElement=图标
AcLabelWidget=标签
AcButtonWidget=按钮
AcNavBarWidget=TabBar
AcListWidget=列表
AcChartWidget=图表
AcCustomWidget=自定义
