# Localized messages for the inforapp widget plugin. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.


###########################################################
# Choice types

	
Choices.acButtonState.disabled=無効
Choices.acButtonState.normal=標準

Choices.acIconPosition.left=左
Choices.acIconPosition.right=右
Choices.acIconPosition.top=上
Choices.acIconPosition.bottom=下

Choices.acIconSize.small=小
Choices.acIconSize.medium=中
Choices.acIconSize.large=大


###########################################################
# Widget elements

AcIconElement=アイコン
AcLabelWidget=ラベル
AcButtonWidget=ボタン
AcNavBarWidget=タブバー
AcListWidget=リスト
AcChartWidget=グラフ
AcCustomWidget=カスタム
